# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "kalilinux/rolling" 
    
    config.vm.provider "vmware_desktop" do |v|
        v.gui = true       
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
    end

    config.vm.provision "shell", privileged: false, path: "tools_install.sh"
end